--<ScriptOptions statementTerminator="!"/>

CREATE TABLE EMP226.l3pe (
		EMPID INTEGER NOT NULL
	)
	DATA CAPTURE NONE!

CREATE TABLE EMP226.l3pf (
		EMPID INTEGER NOT NULL
	)
	DATA CAPTURE NONE!

CREATE TABLE EMP226.l3pg (
		EMPID INTEGER NOT NULL
	)
	DATA CAPTURE NONE!

